In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tensor1 = tf.constant(value=[1, 2, 3], dtype=tf.float32)
tensor1

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [3]:
tensor2 = tf.ones(shape=(3, 2), dtype=tf.int32)
tensor2

# tf.ones(shape, dtype=tf.float32, name=None)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 1]])>

In [4]:
tensor3 = tf.ones_like(input=tensor1)
tensor3
# tf.ones_like(input, dtype=None, name=None)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [5]:
tensor4 = tf.zeros(shape=(3, 3))
tensor4
# tf.zeros(shape, dtype=tf.float32, name=None)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [6]:
tensor5 = tf.zeros_like(input=tensor2)
tensor5
# tf.zeros_like(input, dtype=None, name=None)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0],
       [0, 0]])>

In [7]:
tensor5 = tf.eye(num_rows=5, num_columns=3, batch_shape=None, dtype=tf.dtypes.float32, name=None)
tensor5
# tf.eye(num_rows, num_columns=None, batch_shape=None, dtype=tf.dtypes.float32, name=None)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [8]:
tensor6 = tf.eye(num_rows=2, num_columns=2, batch_shape=None, dtype=tf.dtypes.float32, name=None)
tensor6

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

In [9]:
tensor7 = tf.eye(num_rows=2, num_columns=2, batch_shape=(2, 2), dtype=tf.dtypes.int32, name=None)
tensor7

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[1, 0],
         [0, 1]],

        [[1, 0],
         [0, 1]]],


       [[[1, 0],
         [0, 1]],

        [[1, 0],
         [0, 1]]]])>

In [10]:
tensor7.shape, tensor7.dtype

(TensorShape([2, 2, 2, 2]), tf.int32)

In [11]:
tensor8 = tf.cast(x=tensor7, dtype=tf.dtypes.float32, name=None)
tensor8

# Cast function can convert the types of one variable.

# tf.cast(x, dtype, name=None)

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]]],


       [[[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]]]], dtype=float32)>

In [12]:
tf1 = tf.constant(value=[[1, 2, 3]])
tf2 = tf.constant(value=[[4, 5, 6]])
tensor9 = tf.concat(values=[tf1, tf2], axis=1, name="concat")
tensor9

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6]])>

In [13]:
tensor10 = tf.concat(values=[tf1, tf2], axis=0, name="concat")
tensor10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [14]:
tf.rank(input=tensor10, name=None)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [15]:
tensor11 = tf.constant(value=[[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print(tensor11.ndim)
print(tf.rank(input=tensor11))

2
tf.Tensor(2, shape=(), dtype=int32)


In [16]:
tensor12 = tf.constant(value=[[[1, 1, 1], [2, 2, 2], [3, 3, 3]]])
print(tf.rank(input=tensor12))

tf.Tensor(3, shape=(), dtype=int32)


In [17]:
tf.size(tensor12)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [18]:
tensor13 = tf.random.normal(
    shape = (3, 3),
    mean = 10.0,
    stddev = 0.0,
    dtype = tf.float32,
    seed = 10, 
    name = None
)
tensor13

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]], dtype=float32)>

In [19]:
result = 0
for element in tensor13:
    result += sum(element)
print(result / 9)

tf.Tensor(10.0, shape=(), dtype=float32)


In [20]:
# tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)

tensor14 = tf.random.uniform(
    shape=(3, 3),
    minval = 10,
    maxval = 20,
    dtype = tf.dtypes.int32,
    seed = 5,
    name = None
)
tensor14

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[11, 19, 14],
       [19, 12, 14],
       [19, 17, 16]])>

In [26]:
tensor15 = tf.constant(value=[1, 2, 3, 4, 5, 6])
print(tensor15)
print(tensor15[0])
print(tensor15[-1])
print(tensor15[0:3])

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [32]:
tensor16 = tf.range(start=10, limit=50, delta=5)
print(tensor16)
print(tensor16[0:4])
print(tensor16[2:5])
print(tensor16[1:6:2])
print(tensor16[0:-1])

tf.Tensor([10 15 20 25 30 35 40 45], shape=(8,), dtype=int32)
tf.Tensor([10 15 20 25], shape=(4,), dtype=int32)
tf.Tensor([20 25 30], shape=(3,), dtype=int32)
tf.Tensor([15 25 35], shape=(3,), dtype=int32)
tf.Tensor([10 15 20 25 30 35 40], shape=(7,), dtype=int32)


In [40]:
tensor17 = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(tensor17)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [41]:
tensor17[0:2, 0:2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]])>

In [44]:
tensor17[2, 2]

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [45]:
tensor17[1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6])>

In [47]:
tensor17[0:3, 1:2]

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[2],
       [5],
       [8]])>

In [48]:
tensor17[0:3, 1:3]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6],
       [8, 9]])>

In [49]:
tensor17[:, 0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 7])>

In [50]:
tensor17[..., 0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 7])>

In [61]:
tensor18 = tf.constant([[[1, 2, 0],
                         [3, 5, -1]],
                       [[10, 2, 0],
                        [1, 0, 2]]])
print(tensor18)
print(tensor18.ndim)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]], shape=(2, 2, 3), dtype=int32)
3


In [65]:
ss = tf.constant([[[1, 2, 3], [4, 5, 6]]])
print(ss)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)


In [68]:
x_abs = tf.constant(value=[-2.25, 3.25])
tf.abs(x=x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [69]:
tf.constant(value=tf.abs(x=0.2))

<tf.Tensor: shape=(), dtype=float32, numpy=0.2>

In [70]:
tf.constant(value=tf.abs(x=-0.5))

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [74]:
tf.sqrt(x=(-2.25)**2)

<tf.Tensor: shape=(), dtype=float32, numpy=2.25>

In [77]:
tf.sqrt(x=9.0)

# x value must be float

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [79]:
tf.divide(x=9, y=3)

<tf.Tensor: shape=(), dtype=float64, numpy=3.0>

In [80]:
tf.divide(x=[3, 3, 3], y=[1, 1, 1])

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 3., 3.])>

In [81]:
tf.divide(x=[[9, 12, 15]], y=[[3, 4, 5]])

<tf.Tensor: shape=(1, 3), dtype=float64, numpy=array([[3., 3., 3.]])>

In [82]:
tf.divide(x=9, y=0)

<tf.Tensor: shape=(), dtype=float64, numpy=inf>

In [86]:
tf.math.divide_no_nan(x=9, y=0)

<tf.Tensor: shape=(), dtype=float64, numpy=0.0>

In [91]:
x_1 = tf.constant(value=[5, 3, 6, 6, 4, 6], dtype=tf.float32)
x_2 = tf.constant(value=[7], dtype=tf.float32)
x_2_stretched = tf.constant(value=[7, 7, 7, 7, 7, 7], dtype=tf.float32)

print(tf.math.add(x=x_1, y=x_2))
print(tf.math.add(x=x_1, y=x_2_stretched))

tf.Tensor([12. 10. 13. 13. 11. 13.], shape=(6,), dtype=float32)
tf.Tensor([12. 10. 13. 13. 11. 13.], shape=(6,), dtype=float32)


In [93]:
x_1 = tf.constant(value=[5, 3, 6, 6, 4, 6], dtype=tf.float32)
x_2 = tf.constant(value=[7], dtype=tf.float32)
x_2_stretched = tf.constant(value=[7, 7, 7, 7, 7, 7], dtype=tf.float32)

print(tf.math.multiply(x=x_1, y=x_2))
print(tf.math.multiply(x=x_1, y=x_2_stretched))

tf.Tensor([35. 21. 42. 42. 28. 42.], shape=(6,), dtype=float32)
tf.Tensor([35. 21. 42. 42. 28. 42.], shape=(6,), dtype=float32)


In [95]:
x_1 = tf.constant(value=[5, 3, 6, 6, 4, 6], dtype=tf.float32)
x_2 = tf.constant(value=[[7], [6], [3]], dtype=tf.float32)
#x_2_stretched = tf.constant(value=[7, 7, 7, 7, 7, 7], dtype=tf.float32)

print(tf.math.multiply(x=x_1, y=x_2))

tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [30. 18. 36. 36. 24. 36.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [98]:
x_argmax = tf.constant(value=[200, 100, 50, 150, 250])
print(tf.math.argmax(input=x_argmax))

# argmax function gives us the index of max value in the tensor
# tf.math.argmax(input, axis=None, output_type=tf.int64, name=None)

tf.Tensor(4, shape=(), dtype=int64)


In [101]:
print(tf.math.argmin(input=x_argmax))

# argmin function gives us the index of max value in the tensor

tf.Tensor(2, shape=(), dtype=int64)


In [110]:
x_argmax = tf.constant(value=[
    [2, 20, 30, 3, 6],
    [3, 11, 16, 1, 8],
    [14, 45, 23, 5, 27]
])
print(x_argmax.shape)
print(tf.math.argmax(input=x_argmax, axis=0))
print(tf.math.argmax(input=x_argmax, axis=1))

(3, 5)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([2 2 1], shape=(3,), dtype=int64)


In [112]:
print(tf.math.argmin(input=x_argmax, axis=0))
print(tf.math.argmin(input=x_argmax, axis=1))

tf.Tensor([0 1 1 1 0], shape=(5,), dtype=int64)
tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [97]:
?tf.math.argmax

Signature: tf.math.argmax(input, axis=None, output_type=tf.int64, name=None)
Docstring:
Returns the index with the largest value across axes of a tensor.

In case of identity returns the smallest index.

For example:

>>> A = tf.constant([2, 20, 30, 3, 6])
>>> tf.math.argmax(A)  # A[2] is maximum in tensor A
<tf.Tensor: shape=(), dtype=int64, numpy=2>
>>> B = tf.constant([[2, 20, 30, 3, 6], [3, 11, 16, 1, 8],
...                  [14, 45, 23, 5, 27]])
>>> tf.math.argmax(B, 0)
<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 2, 0, 2, 2])>
>>> tf.math.argmax(B, 1)
<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 2, 1])>
>>> C = tf.constant([0, 0, 0, 0])
>>> tf.math.argmax(C) # Returns smallest index in case of ties
<tf.Tensor: shape=(), dtype=int64, numpy=0>

Args:
  input: A `Tensor`.
  axis: An integer, the axis to reduce across. Default to 0.
  output_type: An optional output dtype (`tf.int32` or `tf.int64`). Defaults
    to `tf.int64`.
  name: An optional name for the operati

In [92]:
?tf.math.multiply

Signature: tf.math.multiply(x, y, name=None)
Docstring:
Returns an element-wise x * y.

For example:

>>> x = tf.constant(([1, 2, 3, 4]))
>>> tf.math.multiply(x, x)
<tf.Tensor: shape=(4,), dtype=..., numpy=array([ 1,  4,  9, 16], dtype=int32)>

Since `tf.math.multiply` will convert its arguments to `Tensor`s, you can also
pass in non-`Tensor` arguments:

>>> tf.math.multiply(7,6)
<tf.Tensor: shape=(), dtype=int32, numpy=42>

If `x.shape` is not the same as `y.shape`, they will be broadcast to a
compatible shape. (More about broadcasting
[here](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).)

For example:

>>> x = tf.ones([1, 2]);
>>> y = tf.ones([2, 1]);
>>> x * y  # Taking advantage of operator overriding
<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
     [1., 1.]], dtype=float32)>

The reduction version of this elementwise operation is `tf.math.reduce_prod`

Args:
  x: A Tensor. Must be one of the following types: `bfloat16`,
    `half`, `float32`

In [89]:
?tf.math.add

Signature: tf.math.add(x, y, name=None)
Docstring:
Returns x + y element-wise.

Example usages below.

Add a scalar and a list:

>>> x = [1, 2, 3, 4, 5]
>>> y = 1
>>> tf.add(x, y)
<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6],
dtype=int32)>

Note that binary `+` operator can be used instead:

>>> x = tf.convert_to_tensor([1, 2, 3, 4, 5])
>>> y = tf.convert_to_tensor(1)
>>> x + y
<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6],
dtype=int32)>

Add a tensor and a list of same shape:

>>> x = [1, 2, 3, 4, 5]
>>> y = tf.constant([1, 2, 3, 4, 5])
>>> tf.add(x, y)
<tf.Tensor: shape=(5,), dtype=int32,
numpy=array([ 2,  4,  6,  8, 10], dtype=int32)>

**Warning**: If one of the inputs (`x` or `y`) is a tensor and the other is a
non-tensor, the non-tensor input will adopt (or get casted to) the data type
of the tensor input. This can potentially cause unwanted overflow or underflow
conversion.

For example,

>>> x = tf.constant([1, 2], dtype=tf.int8)
>>> y = [2

In [85]:
?tf.math.divide_no_nan

Signature: tf.math.divide_no_nan(x, y, name=None)
Docstring:
Computes a safe divide which returns 0 if `y` (denominator) is zero.

For example:

>>> tf.constant(3.0) / 0.0
<tf.Tensor: shape=(), dtype=float32, numpy=inf>
>>> tf.math.divide_no_nan(3.0, 0.0)
<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

Note that 0 is returned if `y` is 0 even if `x` is nonfinite:

>>> tf.math.divide_no_nan(np.nan, 0.0)
<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

Args:
  x: A `Tensor` of a floating or integer dtype.
  y: A `Tensor` with the same dtype as `x` and a compatible shape.
  name: A name for the operation (optional).

Returns:
  The element-wise quotient as in `tf.math.divide(x, y)`,
  except that division by zero produces `0.0`, not `nan`.
File:      c:\users\murat\anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py
Type:      function


In [78]:
?tf.divide

Signature: tf.divide(x, y, name=None)
Docstring:
Computes Python style division of `x` by `y`.

For example:

>>> x = tf.constant([16, 12, 11])
>>> y = tf.constant([4, 6, 2])
>>> tf.divide(x,y)
<tf.Tensor: shape=(3,), dtype=float64,
numpy=array([4. , 2. , 5.5])>

Args:
  x: A `Tensor`
  y: A `Tensor`
  name: A name for the operation (optional).

Returns:
  A `Tensor` with same shape as input
File:      c:\users\murat\anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py
Type:      function


In [73]:
?tf.sqrt

Signature: tf.sqrt(x, name=None)
Docstring:
Computes element-wise square root of the input tensor.

Note: This operation does not support integer types.

>>> x = tf.constant([[4.0], [16.0]])
>>> tf.sqrt(x)
<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
  array([[2.],
         [4.]], dtype=float32)>
>>> y = tf.constant([[-4.0], [16.0]])
>>> tf.sqrt(y)
<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
  array([[nan],
         [ 4.]], dtype=float32)>
>>> z = tf.constant([[-1.0], [16.0]], dtype=tf.complex128)
>>> tf.sqrt(z)
<tf.Tensor: shape=(2, 1), dtype=complex128, numpy=
  array([[0.0+1.j],
         [4.0+0.j]])>

Note: In order to support complex type, please provide an input tensor
of `complex64` or `complex128`.

Args:
  x: A `tf.Tensor` of type `bfloat16`, `half`, `float32`, `float64`,
    `complex64`, `complex128`
  name: A name for the operation (optional).

Returns:
  A `tf.Tensor` of same size, type and sparsity as `x`.

  If `x` is a `SparseTensor`, returns
  `SparseTensor(x.indi

In [67]:
?tf.abs

Signature: tf.abs(x, name=None)
Docstring:
Computes the absolute value of a tensor.

Given a tensor of integer or floating-point values, this operation returns a
tensor of the same type, where each element contains the absolute value of the
corresponding element in the input.

Given a tensor `x` of complex numbers, this operation returns a tensor of type
`float32` or `float64` that is the absolute value of each element in `x`. For
a complex number \\(a + bj\\), its absolute value is computed as
\\(\sqrt{a^2 + b^2}\\).

For example:

>>> # real number
>>> x = tf.constant([-2.25, 3.25])
>>> tf.abs(x)
<tf.Tensor: shape=(2,), dtype=float32,
numpy=array([2.25, 3.25], dtype=float32)>

>>> # complex number
>>> x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
>>> tf.abs(x)
<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

Args:
  x: A `Tensor` or `SparseTensor` of type `float16`, `float32`, `float64`,
    `int32`, `int64`, `complex64` or `complex12

In [27]:
?tf.range

Signature: tf.range(start, limit=None, delta=1, dtype=None, name='range')
Docstring:
Creates a sequence of numbers.

Creates a sequence of numbers that begins at `start` and extends by
increments of `delta` up to but not including `limit`.

The dtype of the resulting tensor is inferred from the inputs unless
it is provided explicitly.

Like the Python builtin `range`, `start` defaults to 0, so that
`range(n) = range(0, n)`.

For example:

>>> start = 3
>>> limit = 18
>>> delta = 3
>>> tf.range(start, limit, delta)
<tf.Tensor: shape=(5,), dtype=int32,
numpy=array([ 3,  6,  9, 12, 15], dtype=int32)>

>>> start = 3
>>> limit = 1
>>> delta = -0.5
>>> tf.range(start, limit, delta)
<tf.Tensor: shape=(4,), dtype=float32,
numpy=array([3. , 2.5, 2. , 1.5], dtype=float32)>

>>> limit = 5
>>> tf.range(limit)
<tf.Tensor: shape=(5,), dtype=int32,
numpy=array([0, 1, 2, 3, 4], dtype=int32)>

Args:
  start: A 0-D `Tensor` (scalar). Acts as first entry in the range if `limit`
    is not None; otherwise

In [21]:
?tf.random.uniform

Signature:
tf.random.uniform(
    shape,
    minval=0,
    maxval=None,
    dtype=tf.float32,
    seed=None,
    name=None,
)
Docstring:
Outputs random values from a uniform distribution.

The generated values follow a uniform distribution in the range
`[minval, maxval)`. The lower bound `minval` is included in the range, while
the upper bound `maxval` is excluded.

For floats, the default range is `[0, 1)`.  For ints, at least `maxval` must
be specified explicitly.

In the integer case, the random integers are slightly biased unless
`maxval - minval` is an exact power of two.  The bias is small for values of
`maxval - minval` significantly smaller than the range of the output (either
`2**32` or `2**64`).

Examples:

>>> tf.random.uniform(shape=[2])
<tf.Tensor: shape=(2,), dtype=float32, numpy=array([..., ...], dtype=float32)>
>>> tf.random.uniform(shape=[], minval=-1., maxval=0.)
<tf.Tensor: shape=(), dtype=float32, numpy=-...>
>>> tf.random.uniform(shape=[], minval=5, maxval=10, dtyp